### ISSUE TITLE
MVP Search 

### ISSUE THREAD

**Issue by theakatz** [infor-design/website#559]
### Requirements: 
- Typing a query is simply entering text in a field. For initial launch, no typeahead or categorization necessary
- Submitting a query loads a search results page
- Determine what data we have a available through API to display a search results page
- Full page search index 
- Keeping fixed nav at top header
- Can bold content to see what you were searching for highlighted 

### Todo:

- [x] @corpulent to get the end point working, working on search API  (https://github.com/infor-design/website/pull/592)
- [x] @kmahsmith to work on full page search results, inputting search, no results, dismissing a search will look like 
- [x] @jmacaluso711  to implement search on front end 
- [ ] if we use option 2: we need to update all the descriptions in the cms (@theakatz and @kayiuho)
  - [x] Resources
  - [x] Examples
  - [x] Blog (there's no descriptions available for blog content)
  - [ ] Code
  - [ ] Design

**Comment by kmahsmith** [comment]
# Flow

![blank diagram - page 1 28 copy](https://user-images.githubusercontent.com/34688242/40737499-ef5ee894-640e-11e8-8c49-18c37bd29617.png)

# Design
## Search page on static
![search static](https://user-images.githubusercontent.com/34688242/40737703-848e3794-640f-11e8-83ac-04fb4348e561.jpg)

## Search with no results 
![search no results](https://user-images.githubusercontent.com/34688242/40737824-d745333e-640f-11e8-88b6-702c3497882a.jpg)

Here are three options for search results depending on what information we want to show. I feel like option 2 would be too difficult because the page types are too different and would be pulling in different snippets, from content, to hyperlinks 

## Search Results option 1
- page name
- tree
- hyperlink
![search entry 1](https://user-images.githubusercontent.com/34688242/40737710-8990ee08-640f-11e8-8588-b20008435bd6.jpg)

## Search Results option 2
- page title
- tree
- snippet of description 
![search entry 2](https://user-images.githubusercontent.com/34688242/40737759-b0b113f0-640f-11e8-93e8-53c429480c7e.jpg)

## Search Results option 3
- page title
- tree 
![search entry 3](https://user-images.githubusercontent.com/34688242/40737798-ca12980a-640f-11e8-8a08-7ad0c539181c.jpg)

**Comment by kmahsmith** [comment]
Let me know what you guys think of the 3 options and I can provide specs and responsive designs.

**Comment by jmacaluso711** [comment]
Looks good. I think it makes sense to include the short description in the results as shown in option 2

**Comment by theakatz** [comment]
@corpulent hey artem--how far are you in setting up the back end for this?

**Comment by corpulent** [comment]
@theakatz Chris, John and I had a call today and I briefed them on the backend setup.  The backend is setup, indexing of uploaded docs, and wagtail content works.  Searching also works,  but the design needs to accommodate for which pages the user needs to search in.  Right now its too general,  we are only searching the `title` of the parent `Page` object that ALL of our pages inherit.  So if you want to get specific,  and search within components,  we would need some kind of a selector on the frontend that specifies the page type to search.

**Comment by kmahsmith** [comment]
@jmacaluso711 wanna meet to fill me in on this, so I can adjust designs.

**Comment by jmacaluso711** [comment]
Yeah sure.. let me know when is good. i'm pretty open

**Comment by kmahsmith** [comment]
@corpulent john told told me about the restrictions. However, I'm wondering if the front-end could possibly not reflect these restrictions of faceted search. From a user perspective, it might not be the best experience. Search is meant to be open ended, so when a user doesn't know what category to look in they can rely on search to help them. If a user needs to fulfill predetermined categories prior to search, it may not be as effective.

What would the level of effort be to have the front-end remain a more traditional search, while the backend handles these restrictions?

**Comment by jmacaluso711** [comment]
@kayiuho Did we come to a consensus on what content the search results should include? Are we going with Option 3?

**Comment by kayiuho** [comment]
@jmacaluso711 I'm not sure. Are both option 2 and 3 do-able? and we just need to choose one?

**Comment by clepore** [comment]
This is not merged into master yet, but will be closed when we do. I'm creating a new ticket as this one is getting an bit long.

In the meantime, https://github.com/infor-design/website/issues/642 is the next step to completing this ticket.
