### ISSUE TITLE
Feedback Thumbs up/down: Add local internal tracking to our DB and API

### ISSUE THREAD

**Issue by clepore** [infor-design/website#648]
**Is your feature request related to a problem? Please describe.**
See the 👍 👎 information on #590 

**Describe the solution you'd like**
- [x] Database migration to add 👍and 👎columns in the pages table
- [x] Add custom post endpoint
- [x] Build the counts display on the front-end
- [ ] #647 Migrate info from GA

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by jmacaluso711** [comment]
Just occurred to me that there is no page model for code docs pages. How would we store the 👍 and 👎  for them?

**Comment by nickwynja** [comment]
Damn. I guess we do have to create a new table for this.

**Comment by clepore** [comment]
That's not too bad. At least it follows DB normalization and not having super larger tables.

**Comment by jmacaluso711** [comment]
@nickwynja if you want to get this up and running locally:
`make shell_backend`
`python3 manage.py migrate`
`make dev_backend`

and I've been using Postman to test posting to `http://localhost:9002/api/feedback/thumbs-down/` and `http://localhost:9002/api/feedback/thumbs-down/`
